export const dialogs = [{
    text1: '<span class="left"><div class="man-perfil"></div> - Hello how are you?</span>',
    text2: '<span class="right">I am <span class="response"></span> thanks - <div class="woman-perfil"></div></span>',
    text3: '<span class="left"><div class="man-perfil"></div> - How <span class="response2"></span> are you? </span>',
    text4: '<span class="right"> <span class="response3"></span> 17 years old and you? - <div class="woman-perfil"></div></span></span>',
    text5: '<span class="left"><div class="man-perfil"></div> - Im 20 <span class="response4"></span> old </span>',
    btn1: 'years',
    btn2: 'old',
    btn3: 'I am',
    btn4: 'fine',
    r1: 'fine',
    r2: 'old',
    r3: 'I am',
    r4: 'years',
},{
    text1: '<span class="left"><div class="oldman-perfil"></div> - Excuse me, <span class="response"></span> is name?</span>',
    text2: '<span class="right"> My name is Jessica, what is <span class="response2"></span>? - <div class="womanTwo-perfil"></div></span>',
    text3: '<span class="left"><div class="oldman-perfil"></div> - John </span>',
    text4: '<span class="right"> You <span class="response3"></span> english very well - <div class="womanTwo-perfil"></div></span>',
    text5: '<span class="left"><div class="oldman-perfil"></div> - <span class="response4"></span> you </span>',
    btn1: 'thank',
    btn2: 'yours',
    btn3: 'what',
    btn4: 'speak',
    r1: 'what',
    r2: 'yours',
    r3: 'speak',
    r4: 'thank',
}
,{
    text1: '<span class="left"><i class="fa fa-user-circle-o" aria-hidden="true"></i> - Hi Sarah, how are you?</span>',
    text2: '<span class="right"> Fine, <span class="response"></span> are you doing? - <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text3: '<span class="left"><i class="fa fa-user-circle-o" aria-hidden="true"></i> - Ok </span>',
    text4: '<span class="right">  What do you <span class="response2"></span> to do? - <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text5: '<span class="left"><i class="fa fa-user-circle-o" aria-hidden="true"></i> - I’m hungry. I’d like to <span class="response3"></span> something. </span>',
    text6: '<span class="right"> Where do you want to <span class="response4"></span>? - <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text7: '<span class="left"><i class="fa fa-user-circle-o" aria-hidden="true"></i> - I’d like to go to an Italian <span class="response5"></span></span>',
    btn1: 'want',
    btn2: 'eat',
    btn3: 'go',
    btn4: 'how',
    btn5: 'restaurant',
    r1: 'how',
    r2: 'want',
    r3: 'eat',
    r4: 'go',
    r5: 'restaurant',
}]

