export const dialogs = [{
    text1: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - Hello how are you?</span>',
    text2: '<span>I am <span class="response"></span> thanks - <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text3: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - How <span class="response2"></span> are you? </span>',
    text4: '<span> <span class="response3"></span> 17 years old and you? - <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text5: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - Im 20 <span class="response4"></span> old </span>',
    btn1: 'years',
    btn2: 'old',
    btn3: 'I am',
    btn4: 'fine',
    r1: 'fine',
    r2: 'old',
    r3: 'I am',
    r4: 'years',
},{
    text1: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - Excuse me, <span class="response"></span> is name?</span>',
    text2: '<span> My name is Jessica, what is <span class="response2"></span>? - <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text3: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - John </span>',
    text4: '<span> You <span class="response3"></span> english very well - <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text5: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - <span class="response4"></span> you </span>',
    btn1: 'thank',
    btn2: 'yours',
    btn3: 'what',
    btn4: 'speak',
    r1: 'what',
    r2: 'yours',
    r3: 'speak',
    r4: 'thank',
}
,{
    text1: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - Hi Sarah, how are you?</span>',
    text2: '<span> Fine, <span class="response"></span> are you doing? - <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text3: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - Ok </span>',
    text4: '<span>  What do you <span class="response2"></span> to do? - <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text5: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - I’m hungry. I’d like to <span class="response3"></span> something. </span>',
    text6: '<span> Where do you want to <span class="response4"></span>? - <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text7: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - I’d like to go to an Italian <span class="response5"></span></span>',
    btn1: 'want',
    btn2: 'eat',
    btn3: 'go',
    btn4: 'how',
    btn5: 'restaurant',
    r1: 'how',
    r2: 'want',
    r3: 'eat',
    r4: 'go',
    r5: 'restaurant',
}
,{
    text1: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - Mary, would you like to <span class="response"></span> something to eat with me?</span>',
    text2: '<span>OK. When?. - <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text3: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - At 10 <span class="response2"></span>. </span>',
    text4: '<span> 10 in the morning? - <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text5: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - No, at <span class="response3"></span>. </span>',
    text6: '<span> Sorry, that’s too late. I <span class="response4"></span> go to <span class="response5"></span> around 10:00PM.- <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text7: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - OK, how about 1:30 PM?</span>',
    text8: '<span> No, that’s too <span class="response6"></span>. I’ll still be at work then. - <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text9: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - OK, how about 1:30 PM?</span>',
    text10: '<span> How about 5:00PM?. - <i class="fa fa-user-circle" aria-hidden="true"></i></span>',
    text11: '<span><i class="fa fa-user-circle-o" aria-hidden="true"></i> - That’s fine.span>',
    btn1: 'night',
    btn2: 'bed',
    btn3: 'get',
    btn4: 'usually',
    btn5: 'early',
    btn6: 'O’clock',
    r1: 'get',
    r2: 'O’clock',
    r3: 'night',
    r4: 'usually',
    r5: 'bed',
    r6: 'early',
}]

export const listenAndLearning = [{

}]

