export const translate = [{
    text: 'How are you',
    t1: 'como',
    t2: 'vai',
    t3: 'você',
    btn1: 'como',
    btn2: 'Anda',
    btn3: 'vai',
    btn4: 'você',
    btn5: 'A',
}, {
    text: 'hello let’s play',
    t1: 'ola',
    t2: 'vamos',
    t3: 'brincar',
    btn1: 'como',
    btn2: 'vamos',
    btn3: 'ola',
    btn4: 'brincar',
    btn5: 'com',
}, {
    text: 'How are you',
    t1: 'como',
    t2: 'vai',
    t3: 'você',
    btn1: 'como',
    btn2: 'Anda',
    btn3: 'vai',
    btn4: 'você',
    btn5: 'A',
},{
    text: 'How are you',
    t1: 'como',
    t2: 'vai',
    t3: 'você',
    btn1: 'como',
    btn2: 'Anda',
    btn3: 'vai',
    btn4: 'você',
    btn5: 'A',
}]